config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
  root'home#index'
  get'home/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pin.rb
class Pin < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :pins
       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]



  # GET /pins or /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1 or /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins or /pins.json
  def create
    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to pin_url(@pin), notice: "Pin was successfully created." }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1 or /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to pin_url(@pin), notice: "Pin was successfully updated." }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1 or /pins/1.json
  def destroy
    @pin.destroy

    respond_to do |format|
      format.html { redirect_to pins_url, notice: "Pin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pin_params
      params.require(:pin).permit(:description)
    end
  def correct_user
    @pin = current_user.pins.find_by(id: params[:id])
    redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/home/_header.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'About Us', home_about_path %>
<nav class="navbar navbar-default" role="navigation">
<div class="container">
<!-- Brand and toggle get grouped for better mobile display -->
<div class="navbar-header">
<button type="button" class="navbar-toggle collapsed" data6 toggle="collapse" data-target="#bs-example-navbar-collapse-1"> 
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<%= link_to 'Ruby on Rails', root_path, class: 'navbar-brand' %>
</div>
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
<ul class="nav navbar-nav navbar-right">
<li><%= link_to 'Home', root_path %></li>
<li><%= link_to 'About Me', home_about_path %></li>
<li><%= link_to 'List Pins', pins_path %></li>
<% if user_signed_in? %>
   <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
   <li><%= link_to 'Add Pin', new_pin_path %></li>
   <%= form_tag(destroy_user_session_path, method: :delete) do %>
   <%= submit_tag 'Log Out' %>
<% end %>
   <% else %>
   <li><%= link_to "Login", new_user_session_path %></li>
   <li><%= link_to "Join", new_user_registration_path %></li>
   <% end %>
</ul>
</div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>

app/views/home/about.html.erb
<h1>About Me...</h1>
2 <p>My Name Is Bozhidar and I'm Building a Pinterest Clone</p>

app/views/home/index.html.erb
<div class="jumbotron">
 <h1>Hello madafaka!</h1>
 <p>It's Gonna Kick All Ass!</p>
 <%= link_to 'About Us', home_about_path, class: 'btn btn-default' %>
 <%= link_to 'Home', root_path, class: 'btn btn-primary' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Helloworld</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'home/header' %>
    <div class="container">
      <% flash.each do |name, msg| %>
       <%= content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>
       <%= yield %>
    </div>
   
  </body>
</html>

app/views/pins/_form.html.erb
<%= form_with(model: pin) do |form| %>
  <% if pin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
        <% pin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<div id="<%= dom_id pin %>">
  <p>
    <strong>Description:</strong>
    <%= pin.description %>
  </p>

</div>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render "form", pin: @pin %>

<br>

<div>
  <%= link_to "Show this pin", @pin %> |
  <%= link_to "Back to pins", pins_path %>
</div>

app/views/pins/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pins:</h1>

<div id="pins">
  <% @pins.each do |pin| %>
    <%= render pin %>
    <p>
      <%= link_to "Pin details", pin %>
    </p>
  <% end %>
</div>

<%= link_to "New pin", new_pin_path %>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render "form", pin: @pin %>

<br>

<div>
  <%= link_to "Back to pins", pins_path %>
</div>

app/views/pins/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pin %>

<div>
  <% if @pin.user == current_user %>
    <%= link_to "Edit this pin", edit_pin_path(@pin) %> |
  <% end %>
  <%= link_to "Back to pins", pins_path %>
  <% if @pin.user == current_user %>
    <%= button_to "Destroy this pin", @pin, method: :delete %>
  <% end %>  
</div>